### PR TITLE
Goodness Of Fit

### PR DESCRIPTION
**Pull request by ricleal**
Hi,

I created an extra parameter: `goodnessOfFit` (`R^2`) that would be great to have in the fitting result.
I'd appreciate if you made that available for packaging. I hope I have followed your development practices :)
Thanks
Ricardo

### CODE REVIEW

**Comment by maasencioh** [comment]
Hello @ricleal, we highly appreciate the time that you have to spend doing this, but we currently have a way of doing the Rˆ2 and chi-square calculation. [This is done in the super class](https://github.com/mljs/regression-base/blob/bb11ce6e1362a4bc8a6a692bde7ceb2cfa9acf7b/src/index.js#L47-L84), but any feedback on how you'll like to use it will be very valuable for us.

**Comment by ricleal** [comment]
I feel dumb now... :)
Do you have any example where you use both?
I just need to print the goodness of fit once the LM finishes...

**Comment by ricleal** [comment]
No worries.. I did it!
It's pretty simple.
Thanks again

**Comment by maasencioh** [comment]
@ricleal don't worry, I guess that we should document this better in order to avoid future confusions, thank you!

**Pull request closed without merging**
