### PR TITLE
Clean up tests

### LINKED ISSUE #24: TODO: make test structure consistent (`describe... it...` instead of `test`)
https://github.com/mljs/levenberg-marquardt/blob/afbbd9055d539bc120180d4cfb35d7371941f1c2/src/__tests__/curve.js#L41

### PR DESCRIPTION
**Pull request by jacobq**
Before I get too much further into this I'd like some feedback. 
I'm trying to:

* Reduce the amount of boilerplate / duplicated code
* Eliminate the use of magic numbers
* Groups related tests together and separate unrelated tests
* Simplify tests (ideally just complicated enough to test correct behavior but not any more complex)

Fixes #24

### CODE REVIEW

**Comment by targos** [comment]
Oh, you're still working on it. Please ping me when it's ready :)

**Comment by jacobq** [comment]
@targos Thanks for taking a look. Yeah, sorry, it's ready now :D I just had a few more tweaks to push. Can they merge as-is or do you want them squashed more?

Note that I think we'll want to change some of these behaviors, but it seemed prudent to refactor a bit beforehand to minimize confusion / potential for mistakes. In particular, I think that if the user-provided function (`(...params) => x => ...`) ever evaluates to NaN we should throw an error. Currently we have a test case (`Should stop and return parameterError=NaN if function evaluates to NaN after starting`) where the algorithm wanders into invalid parameters (makes the function return `NaN`), stops, and returns `parameterError: NaN`. If the caller is only looking at `parameterValues` they may not realize there is a problem, and more importantly, these cases should be entirely preventable by using `minValues` and `maxValues` or by adapting the function itself. 

We're also still missing a test for what happens if the function returns `NaN` during initialization (I believe the matrix constructor throws an error in this case right now).

**Comment by jacobq** [comment]
@targos ping ping :wink:

**Comment by targos** [comment]
> Can they merge as-is or do you want them squashed more?

Merge as-is seems fine.

> Note that I think we'll want to change some of these behaviors, but it seemed prudent to refactor a bit beforehand to minimize confusion / potential for mistakes. 

:+1: 

> In particular, I think that if the user-provided function (`(...params) => x => ...`) ever evaluates to NaN we should throw an error. Currently we have a test case (`Should stop and return parameterError=NaN if function evaluates to NaN after starting`) where the algorithm wanders into invalid parameters (makes the function return `NaN`), stops, and returns `parameterError: NaN`. If the caller is only looking at `parameterValues` they may not realize there is a problem, and more importantly, these cases should be entirely preventable by using `minValues` and `maxValues` or by adapting the function itself.

Agreed.

> We're also still missing a test for what happens if the function returns `NaN` during initialization (I believe the matrix constructor throws an error in this case right now).

Let's handle this in a follow-up PR.

**Pull request merged**
